# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 2.7

notifications:
  email:
    - shannon@cruey.net
  webhooks:
    urls:
      - https://postb.in/SZbwsz5w
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
