# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: minimal

notifications:
  email:
    - shannon@cruey.net
  webhooks:
    urls:
      - https://continuum-sandbox.v1host.com/api/accept_webhook?handler=travis-ci&token=58a34c7f5d9e5d0cf7f04855
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
